import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import qs from "qs";
import { getNavigationData } from "../lib/services";
import { fetchLocalesData } from "@/middleware";
import AppBar from "@Components/AppBar/AppBar";
import { getCookie, setCookie } from "../actions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { locales, defaultLocale } = await fetchLocalesData();
  const localeData = await getCookie("userLang");
  console.log("localeData", localeData);

  const locale = localeData?.value ?? defaultLocale;
  console.log("layout", locale);

  // const navQuery = qs.stringify(
  //   { populate: "nested_menu_items", locale: defaultLocale },
  //   { encodeValuesOnly: true }
  // );

  // const navigationData = await getNavigationData(navQuery);

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <AppBar langs={locales} currentLocale={locale} />
        {children}
      </body>
    </html>
  );
}
